Update for enjoi and tape packages, change dev dependencies.
krakenjs/swaggerize-routes pull request #97
Opened 2021-03-08 16:57 UTC by dlobregon

2021-03-08 18:14 UTC, hugoerortiz commented on lib/buildroutes.js
> +/* eslint-disable max-len */
are those exceptions really needed?

2021-03-08 18:14 UTC, rtrys commented on lib/buildroutes.js
> +
looks like some of these variables can be const, and also can you use a line per declaration?

2021-03-08 18:14 UTC, rtrys commented on lib/buildroutes.js
> +
if one of them need to be `let`, can you declare it previous to first assignation?

2021-03-08 18:14 UTC, rtrys commented on lib/buildroutes.js
> +    validator;
can you verify if is it possible to use const for these variables?

2021-03-08 18:14 UTC, rtrys commented on package.json
> +    "node": ">=10"
should it be `>=12`?
latest version of Joi requires node 12

2021-03-08 22:49 UTC, tikochato commented on lib/validator.js
> +  for (let i = 1; i < paths.length && fragment; i++) {
```suggestion
  for (let i = 1; i < paths.length && fragment; i+=1) {
```
We could use the `i += 1` expression or we could add the `"allowForLoopAfterthoughts": true` rule to the eslint config file.

2021-03-09 16:19 UTC, dlobregon commented on lib/buildroutes.js
> +/* eslint-disable max-len */
I'm agree with you, the changes have been done.

2021-03-09 16:20 UTC, dlobregon commented on lib/buildroutes.js
> +
You are right, I applied your suggestion using `const` and `let`.

2021-03-09 16:31 UTC, dlobregon commented on package.json
> +    "node": ">=10"
Thanks, the change is done.

2021-03-09 16:31 UTC, dlobregon commented on lib/validator.js
> +  for (let i = 1; i < paths.length && fragment; i++) {
sure, the change is done.

2021-03-10 05:29 UTC, RobertTheBlair requested changes
This solves issue 94 - please update that issue, bring it to the creator

2021-03-10 05:29 UTC, RobertTheBlair commented on CHANGELOG.md
> +- Update to node v10, add `package-lock.json` file
Should this be v12?

Might also want to make a bigger version jump if we are ruling out old node versions

2021-03-10 05:29 UTC, RobertTheBlair commented on package.json
> +  "version": "1.0.12",
is node 12 minimum a point release?

2021-03-16 18:16 UTC, grawk commented
@dlobregon I've published `2.0.0-alpha.1` and pushed a branch `2.0.0-alpha` back to this repo to keep track of what is published as alpha.

2021-08-16 21:29 UTC, kumarrishav commented on test/test-validation.js
> -        t.ok(detail.path === parameterName, 'Expected error.details.path to equal ' + parameterName);
was it failing earlier? what changed?

2021-08-16 21:31 UTC, kumarrishav commented
looks good to me.

2021-08-16 21:51 UTC, maxmil7 commented
👍

2021-08-16 22:17 UTC, sumeetkakkar commented on .travis.yml
> +  - "12"
Maybe we should add 14

2021-08-16 22:17 UTC, sumeetkakkar commented on lib/readhandlers.js
> +  let handlers; let
Wondering why not `let handlers, obj;`?

2021-08-16 22:17 UTC, sumeetkakkar commented on CHANGELOG.md
> +- Update to node v10, add `package-lock.json` file
+1 on Node 12. Maybe it can be changed to node 10+.
Curious, is package-lock.json for unit tests? Shouldn't unit tests always run on the latest dependency versions?

2021-08-16 22:17 UTC, sumeetkakkar commented on lib/validator.js
> +      const self = this;
I guess this is not needed now, as we are using arrow function.

2021-08-16 22:17 UTC, sumeetkakkar commented on lib/validator.js
> +            return callback(result.error);
Since this function is using `callback`, should we avoid potentially returning a value in validate function?
i.e. change this to
`callback(result.error); return;`

2021-08-16 22:17 UTC, sumeetkakkar commented on lib/validator.js
> +          return callback(null, result.value);
Since this function is using `callback`, should we avoid potentially returning a value in validate function?
i.e. change this to
`callback(null, result.value);`

2021-08-16 22:17 UTC, sumeetkakkar commented on lib/validator.js
> +  let id; let refschema; let path; let fragment; let
This IMO is weird from readability. Should we instead define all as one `let` or define them in separate lines?

2021-08-16 22:22 UTC, sumeetkakkar commented
Few minor comments. Otherwise looks good for semver major.

2021-09-26 08:18 UTC, ESRogs commented
Is anyone able to merge this?

2025-01-31 15:44 UTC, closed without merging